spring:
  application:
    name: BootNest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/boot_nest
    username: pgadmin
    password: 11asddsa

  security:
    user:
      name: user
      password: pa$w0rd

management:
  endpoints:
    web:
      exposure:
        include: '*'
#        exclude: beans
  info:
    env:
      enabled: true

#Actuator /info data
info:
  app:
    name: BootNest
    version: 0.0.1

server:
  port: 8090