logging:
  level:
    org:
      hibernate:
        type: debug

spring:
  application:
    name: BootNest
  main:
    banner-mode: log #off

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

  security:
    user:
      name: user
      password: pa$w0rd

  data:
    rest:
      base-path: /api

management:
  endpoints:
    web:
      exposure:
        include: '*'
#        exclude: beans
  info:
    env:
      enabled: true

#Actuator /info data
info:
  app:
    name: BootNest
    version: 0.0.1

server:
  port: 8090